spring:
  application:
    name: DugOut
  mvc:
    cors:
      mappings:
        /api/**:
          allowed-origins:
            - "http://localhost:3000"
            - "https://dug-out.store"
          allowed-methods: GET,POST,PUT,DELETE,OPTIONS
          allowed-headers: "*"
          allow-credentials: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URL}

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false

# 날씨 데이터 설정
kma:
  base-url: ${KMA_URL}
  service:
    key: ${KMA_KEY}

# JWT 인증
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24시간
