spring:
  application:
    name: DugOut
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always

kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: ${KAKAO_REDIRECT_URL}

# Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  show-actuator: false

# 날씨 데이터 설정
kma:
  base-url: ${KMA_URL}
  service:
    key: ${KMA_KEY}

# JWT 인증
jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000 # 30일 (24시간 * 60분 * 60초 * 1000밀리초 * 30일)

# s3 정보
cloud:
  aws:
    s3:
      bucket: dugout-profile
      path:
        players: players
        userProfile: userProfile
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}
